### ISSUE TITLE
Having 0 TRVs (smartvalves) is a valid configuration

### ISSUE THREAD

**Issue by relaystar** [asantaga/wiserheatingapi#1]
It might not be common, but it is valid, for instance if you buy the 3 zone kit:

https://www.draytoncontrols.co.uk/products/Smart-Heating/Wiser/wiser-thermostat-kit-3

it doesn't come with any TRVs.

**Comment by asantaga** [comment]
mmm yeah.. I'll be fixing the code, need it for the HA  Project

**Comment by asantaga** [comment]
this is now fixed, having a room with no TRVs no longer gives an error.
