### ISSUE TITLE
wiserheatingapi error

### ISSUE THREAD

**Issue by HWO365manager** [asantaga/wiserheatingapi#12]
Running wiserapitest.py I get an error. Here is the relevant part of the error report:-
......\wiserHeatingAPI\wiserHub.py", line 323, in getRoomSchedule
    scheduleId = self.getRoom(roomId).get("ScheduleId")
AttributeError: 'NoneType' object has no attribute 'get'

I am running Drayton Wiser Hub API v 1.0.5 with Python 3.8.1 in Win 10 Version 10.0.18363.592

**Comment by asantaga** [comment]
fixed in 1.0.5.1, 

in the code I assume you had at least 4 rooms, it now assumes 1 room .
