### ISSUE TITLE
Temperature set points have wrong restrictions

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserheatingapi#2]
Hi,

When trying to set a temperature set point on a iTRV, the limit imposed by the Wiser Hub is between 5C and 30C ie (50 and 300) or -200 - being Off.

In the api this limit is set between 1C and 40C and will not allow -20C to allow turning off of the iTRV.

Please could this be updated to allow the correct restrictions of the Hub.

For note, you could remove these restrictions all together as setting outside these parameters gives an Error 400 with the below message returned.

{
    "Error": "Manual override requires a 'SetPoint' between 50 and 300 or -200 (i.e. from 5 to 30 degreesC or Off)"
}

This could suffice as the error message?

Thanks and thanks for a great api!
Mark

**Comment by asantaga** [comment]
yup makes perfect sense. give me a couple of days

**Comment by asantaga** [comment]
fixed
