### ISSUE TITLE
TRV Open/Close and Min/Max Temperature Automation

### ISSUE THREAD

**Issue by charlesomer** [asantaga/wiserheatingapi#26]
Hi, thank you for your great work on this and the Home Assistant plugin!

I just wondered if the api supports opening/closing a TRV manually rather than through setting the temperature (perhaps with the v2 api)?

I'll try to explain my reasoning behind this and what I'm trying to achieve. I have most of the radiators controlled with the smart TRVs and whilst I can set a minimum temperature for each room, once the temperature reaches this point it closes the TRV. What I would like to be able to do is perhaps set a maximum temperature as well so that the TRV remains open until that point but doesn't actually call the boiler for heat unless it's below the minimum temperature.

An example:
I don't need the spare room radiator to have a high minimum temperature because I'm not in there very often, but, if the living room/hallway radiators are calling for heat then it would be good for the spare room TRV to be open too to make use of that heat in case there's washing drying in there or something.

I have considered setting up some sort of automation via home assistant (if it's even possible) where if a radiator is calling for heat because it is below the minimum temperature, then those other TRVs which have not yet reached their max temperature automatically get set to 30 degrees (or something high) which would force them open. Then, once all radiators are over their minimum temperature, all TRVs get set back to their scheduled value as specified by the wiser app.

I hope that makes sense?

Thank you
Charles

**Comment by msp1974** [comment]
Charles,  in short no you canmot do this, even in v2 of the api.  Your automation plan sounds feasable but i would use the demand percentage i stead of monitoring temps as that would be easier and is temp setting independant.MarkSent from my Galaxy

**Comment by charlesomer** [comment]
Thank you for your response and confirming that. The reason I was using the temps and not the demand percentage was because I don't think it would then be possible to work out which TRVs were on because they were below min temperature or on because they are still below max temperature.

I suppose I could use the demand percentage to check that those TRVs which are below the min temperature are definitely calling for heat though.

**Comment by charlesomer** [comment]
Okay so I've quickly created a script that runs via Pyscript for Home Assistant which seems to prove that it is possible. It currently runs every minute but it would be nice if it only ran when necessary (e.g. when temperature changes) but that's something to look into later.

I'll leave this here if anyone is interested. In theory it should work for other heating manufactures as well or at least I've tried to make it modifiable so that it will work.

[https://github.com/charlesomer/home-assistant-trv-opener](https://github.com/charlesomer/home-assistant-trv-opener)
