### ISSUE TITLE
Setting boost temp sometimes errors

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserheatingapi#4]
I have seen a situation whereby setting the boost temp when calling setRoomMode causes an error from the hub that it is expecting an integer.

I think this is caused by the fact that passing a float value (ie 21.5) to the method maintains a float when passing to the hub.

Line 
temp=boost_temp*10

needs to be
temp=int(boost_temp*10)

to ensure this cannot happen

Thx Mark

**Comment by asantaga** [comment]
Hey Mark, I think I fixed this bug earlier on, which version of HA are you using?
(still not got around to fixing my server :-( , xmas lag...)

**Comment by msp1974** [comment]
I am running 103.4 with wiser component 1.7.1.  I can send you a PR but think just need to sent to an integer value when we multiply boost temp by 10.  Think you have fixed this in the setTemperature method but not in the setRoomMode method.

**Comment by msp1974** [comment]
Sorry i was probably remembering a previous version where you were removing the decimal point instead of multiplying by 10. It is true that i cannot recreate this issue right now but i think we maybe should do the integer conversion as suggested to ensure we cannot pass a non integer value to the wiser hub.

**Comment by asantaga** [comment]
Mark,. this issue is fixed with your PR right?

**Comment by msp1974** [comment]
Yes
