### ISSUE TITLE
Ability to get/set schedules for devices

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserheatingapi#8]
Based on comments by @scooper1 https://github.com/asantaga/wiserHomeAssistantPlatform/issues/46

it would be nice to have the ability to set schedules for devices. This would allow rather clever automation from products such as Home assistant, node-red etc and if the wiser app stops working then we could implement an alternative app..

Data for schedules is available from REST GET data/domain/Schedule/{scheduleid}

Shouldnt be too hard to create a service function which is simply get/set schedule for which HA could then use

**Comment by msp1974** [comment]
I was thinking that the api should require the schedule to be in json format. This way we can keep it light and not have to deal with converting from yaml but just push the provided json file in a patch request.

However, in HA we should use a yaml file as
A) it is more standard to HA
B) HA already has a lot of built in fu ctio s we can use to process this file.

What's the thoughts?

**Comment by asantaga** [comment]
Resolved with PR9 from msp1974 (thanks Mark!),
